name: Delivery workflow

on:
  push:
    branches:
    - prototype

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        file: docker/frontend.dockerfile
        context: .
        tags: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/explorers/frontend:${{ github.sha }}
        push: true

    - name: Before Secret
      run: |
        microk8s.kubectl delete secret explorers-registry --ignore-not-found

    - name: Secret
      run: |
        microk8s.kubectl create secret docker-registry explorers-registry \
        --docker-server=${{ secrets.REGISTRY_URL }} \
        --docker-username=${{ secrets.REGISTRY_USERNAME }} \
        --docker-password=${{ secrets.REGISTRY_PASSWORD }} \

    - name: Apply
      run: |
        sed 's#CONTAINER_IMAGE#ghcr.io/joaorodriguesjr/explorers/frontend:${{ github.sha }}#' kubernetes/deployment.yml | microk8s.kubectl apply -f -
        microk8s.kubectl apply -f kubernetes/service.yml
        microk8s.kubectl apply -f kubernetes/ingress.yml

    - name: Rollout
      run: |
        microk8s.kubectl rollout restart deployment.apps/explorers-frontend
